server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tKT3vPRZTEd9Sk6QeRN
    keySecret: IHlIw65Vu5bKYwyuOt1yuLgyMXRhtu
    bucketName: fafujijin-oss
